language: node_js

node_js:
  - 10

dist: trusty

jobs:
  include:
    - stage: build
      script:
        - npm run generate
      deploy:
        provider: pages
        skip_cleanup: true
        commiter_from_gh: true
        github_token: $GITHUB_TOKEN
        on:
          branch: develop
        target_branch: master
        local_dir: dist
